/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/travis-ci/trvs-operator/pkg/apis/travisci/v1"
	scheme "github.com/travis-ci/trvs-operator/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TrvsSecretsGetter has a method to return a TrvsSecretInterface.
// A group's client should implement this interface.
type TrvsSecretsGetter interface {
	TrvsSecrets(namespace string) TrvsSecretInterface
}

// TrvsSecretInterface has methods to work with TrvsSecret resources.
type TrvsSecretInterface interface {
	Create(*v1.TrvsSecret) (*v1.TrvsSecret, error)
	Update(*v1.TrvsSecret) (*v1.TrvsSecret, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.TrvsSecret, error)
	List(opts metav1.ListOptions) (*v1.TrvsSecretList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.TrvsSecret, err error)
	TrvsSecretExpansion
}

// trvsSecrets implements TrvsSecretInterface
type trvsSecrets struct {
	client rest.Interface
	ns     string
}

// newTrvsSecrets returns a TrvsSecrets
func newTrvsSecrets(c *TravisciV1Client, namespace string) *trvsSecrets {
	return &trvsSecrets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the trvsSecret, and returns the corresponding trvsSecret object, and an error if there is any.
func (c *trvsSecrets) Get(name string, options metav1.GetOptions) (result *v1.TrvsSecret, err error) {
	result = &v1.TrvsSecret{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("trvssecrets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of TrvsSecrets that match those selectors.
func (c *trvsSecrets) List(opts metav1.ListOptions) (result *v1.TrvsSecretList, err error) {
	result = &v1.TrvsSecretList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("trvssecrets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested trvsSecrets.
func (c *trvsSecrets) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("trvssecrets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a trvsSecret and creates it.  Returns the server's representation of the trvsSecret, and an error, if there is any.
func (c *trvsSecrets) Create(trvsSecret *v1.TrvsSecret) (result *v1.TrvsSecret, err error) {
	result = &v1.TrvsSecret{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("trvssecrets").
		Body(trvsSecret).
		Do().
		Into(result)
	return
}

// Update takes the representation of a trvsSecret and updates it. Returns the server's representation of the trvsSecret, and an error, if there is any.
func (c *trvsSecrets) Update(trvsSecret *v1.TrvsSecret) (result *v1.TrvsSecret, err error) {
	result = &v1.TrvsSecret{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("trvssecrets").
		Name(trvsSecret.Name).
		Body(trvsSecret).
		Do().
		Into(result)
	return
}

// Delete takes name of the trvsSecret and deletes it. Returns an error if one occurs.
func (c *trvsSecrets) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("trvssecrets").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *trvsSecrets) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("trvssecrets").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched trvsSecret.
func (c *trvsSecrets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.TrvsSecret, err error) {
	result = &v1.TrvsSecret{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("trvssecrets").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
